## 2.1数据操作
为了能够完成各种数据操作，我们需要某种⽅法来存储和操作数据。通常，我们需要做两件重要的事：（1）
获取数据；（2）将数据读⼊计算机后对其进⾏处理。如果没有某种⽅法来存储数据，那么获取数据是没有意
义的。\
⾸先，我们介绍n维数组，也称为张量（tensor）。使⽤过Python中NumPy计算包的读者会对本部分很熟悉。
⽆论使⽤哪个深度学习框架，它的张量类（在MXNet中为ndarray，在PyTorch和TensorFlow中为Tensor）都
与Numpy的ndarray类似。但深度学习框架⼜⽐Numpy的ndarray多⼀些重要功能：⾸先， GPU很好地⽀持加
速计算，⽽NumPy仅⽀持CPU计算；其次，张量类⽀持⾃动微分。这些功能使得张量类更适合深度学习。
### 2.1.1 入门
了解并运行一些基本数值计算⼯具。

In [2]:
# 导入pytorch
import torch

张量表⽰⼀个由数值组成的数组，这个数组可能有多个维度。具有⼀个轴的张量对应数学上的向量（vector）；
具有两个轴的张量对应数学上的矩阵（matrix）；具有两个轴以上的张量没有特殊的数学名称。\
⾸先，我们可以使⽤ arange 创建⼀个⾏向量 x。这个⾏向量包含以0开始的前12个整数，它们默认创建为整
数。也可指定创建类型为浮点数。张量中的每个值都称为张量的 元素（element）。例如，张量 x 中有 12 个
元素。除⾮额外指定，新的张量将存储在内存中，并采⽤基于CPU的计算。

In [19]:
# 使⽤ arange 创建⼀个⾏向量 x
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

可以通过张量的shape属性来访问**张量（沿每个轴的⻓度）的形状。**

In [20]:
x.shape # 张量的形状

torch.Size([12])

如果只想知道张量中元素的总数，即**形状的所有元素乘积**，可以检查它的⼤⼩（size）。因为这⾥在处理的是
⼀个向量，所以它的shape与它的size相同

In [21]:
x.numel() # 张量的大小、元素数量

12

reshapge：改变张量的形状（不改变元素数量和元素值）

In [30]:
x = x.reshape(3,4) # x.reshape(4,3) or x.reshape(2,6) or x.reshape(6,2) or x.reshape(1,12) or x.reshape(12,1)
print(x)
print(x.shape)
print(x.numel())
# 总结：reshape后，形状变，大小不变；限制：形状元素值乘积等于大小。

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])
torch.Size([3, 4])
12


reshapge：自动推断 -1 \
在知道宽度后，⾼度会被⾃动计算得出，不必我们⾃⼰做除法\
我们可以通过-1来调⽤此⾃动计算出维度的功能。即我们可以
⽤x.reshape(-1,4)或x.reshape(3,-1)来取代x.reshape(3,4)。

In [36]:
x = x.reshape(1,-1) # x.reshape(-1,3) or x.reshape(2,-1) or x.reshape(1,-1) or x.reshape(-1,1) 等
print(x)
print(x.shape)
print(x.numel())

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]])
torch.Size([1, 12])
12


有时，我们希望使⽤全0、全1、其他常量，或者从特定分布中随机采样的数字来初始化矩阵。我们可以创建
⼀个形状为（2,3,4）的张量，其中所有元素都设置为0。

In [41]:
x = torch.zeros((2,3,4))
x

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

同样，我们可以创建⼀个形状为(2,3,4)的张量，其中所有元素都设置为1。

In [42]:
x = torch.ones((2,3,4))
x

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

有时我们想通过从某个特定的概率分布中随机采样来得到张量中每个元素的值。\
例如，当我们构造数组来作为神经⽹络中的参数时，我们通常会随机初始化参数的值 \
创建⼀个形状为（3,4）的张量。其中的每个元素都从均值为0、标准差为1的标准⾼斯分布（正态分布）中随机采样。\

In [45]:
x = torch.randn((3,4))
x

tensor([[-0.5315,  0.1060,  0.6054,  0.1926],
        [ 0.3659,  1.1652, -1.1786, -0.8112],
        [-0.3151, -0.5881, -0.0896,  0.4123]])

我们还可以通过提供包含数值的Python列表（或嵌套列表），来为所需张量中的每个元素赋予确定值。在这
⾥，最外层的列表对应于轴0，内层的列表对应于轴1。

In [48]:
x = torch.tensor([[1,2,3,4],[4,6,4,7],[6,4,2,7]])
print(x)
print(x.shape) # 最外层的列表对应于轴0，内层的列表对应于轴1。 第0轴是3个元素，第1轴是4个元素
print(x.numel())

tensor([[1, 2, 3, 4],
        [4, 6, 4, 7],
        [6, 4, 2, 7]])
torch.Size([3, 4])
12


### 2.1.2 运算符
对于任意具有相同形状的张量，常⻅的标准算术运算符（+、 -、 *、 /和**）都可以被升级为按元素运算。我
们可以在同⼀形状的任意两个张量上调⽤按元素操作。在下⾯的例⼦中，我们使⽤逗号来表⽰⼀个具有5个
元素的元组，其中每个元素都是按元素操作的结果。

In [49]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2])
x+y, x-y, x*y, x/y, x**y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

“按元素”⽅式可以应⽤更多的计算，包括像求幂这样的⼀元运算符

In [50]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

除了按元素计算外，我们还可以执⾏线性代数运算，包括向量点积和矩阵乘法。我们将在 2.3节中解释线性代数的重点内容。\
我们也可以**把多个张量连结（concatenate）在⼀起**，注意形状要相同，把它们端对端地叠起来形成⼀个更⼤的张量。我们只需要提供张量列表，并给出沿哪个轴连结。\
下⾯的例⼦分别演⽰了当我们沿⾏（轴-0，形状的第⼀个元素）和按列（轴-1，形状的第⼆个元素）连结两个矩阵时，会发⽣什么情况。\
我们可以看到，第⼀个输出张量的轴-0⻓度（6）是两个输⼊张量轴-0⻓度的总和（3 + 3）；第⼆个输出张量的轴-1⻓度（8）是两个输⼊张量轴-1⻓度的总和（4 + 4）。

In [14]:
x = torch.arange(12,dtype=torch.float32).reshape((3,4))
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
print(x.shape) # [3, 4]
print(y.shape) # [3, 4]
torch.cat((x,y), dim=0) # shape = [6,4]
torch.cat((x,y), dim=1) # shape = [3,8]

torch.Size([3, 4])
torch.Size([3, 4])


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符来构建张量 \
以X == Y为例：对于每个位置，如果X和Y在该位置相等，则新张量中相应项的值为1。这意味着逻辑语句X == Y在该位置处为真，否则该位置为0。

In [20]:
print(x)
print(y)
x == y

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])


tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进⾏求和，会产⽣⼀个单元素张量

In [26]:
x.sum()

tensor(66.)

### 2.1.3 广播机制
在上⾯的部分中，我们看到了如何在相同形状的两个张量上执⾏按元素操作。在某些情况下，即使形状不同，我们仍然可以通过调⽤ ⼴播机制（broadcasting mechanism）来执⾏按元素操作。这种机制的⼯作⽅式如
下：\
1. 通过适当复制元素来扩展⼀个或两个数组，以便在转换之后，两个张量具有相同的形状；
2. 对⽣成的数组执⾏按元素操作。
在⼤多数情况下，我们将沿着数组中⻓度为1的轴进⾏⼴播，如下例⼦：

In [35]:
a = torch.arange(3)
print(a)
a_reshape = a.reshape((3,1))
print(a_reshape)
b = torch.arange(2)
print(b)
b_reshape = b.reshape((1,2))
print(b_reshape)

tensor([0, 1, 2])
tensor([[0],
        [1],
        [2]])
tensor([0, 1])
tensor([[0, 1]])


由于a和b分别是3 × 1和1 × 2矩阵，如果让它们相加，它们的形状不匹配。我们将两个矩阵⼴播为⼀个更⼤的3 × 2矩阵，如下所⽰：矩阵a将复制列，矩阵b将复制⾏，然后再按元素相加。

In [37]:
a_reshape + b_reshape

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.4 索引和切片
就像在任何其他Python数组中⼀样，张量中的元素可以通过索引访问。与任何Python数组⼀样：第⼀个元素的索引是0，最后⼀个元素索引是-1；可以指定范围以包含第⼀个元素和最后⼀个之前的元素。
如下所⽰，我们可以⽤[-1]选择最后⼀个元素，可以⽤[1:3]选择第⼆个和第三个元素：

In [50]:
x = torch.arange(12).reshape((3,4))
print(x)
x[-1],x[1:3]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


(tensor([ 8,  9, 10, 11]),
 tensor([[ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]))

除读取外，我们还可以通过指定索引来将元素写⼊矩阵。

In [51]:
x[1,2] = 9
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  9,  7],
        [ 8,  9, 10, 11]])

如果我们想为多个元素赋值相同的值，我们只需要索引所有元素，然后为它们赋值。例如， [0:2, :]访问第1⾏和第2⾏，其中“:”代表沿轴1（列）的所有元素。虽然我们讨论的是矩阵的索引，但这也适⽤于向量和超过2个维度的张量。

In [52]:
x[0:2, :] = 12
x

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])

### 2.1.5 节省内存
运⾏⼀些操作可能会导致为新结果分配内存。例如，如果我们⽤Y = X + Y，我们将取消引⽤Y指向的张量，⽽是指向新分配的内存处的张量。
在下⾯的例⼦中，我们⽤Python的id()函数演⽰了这⼀点，它给我们提供了内存中引⽤对象的确切地址。运⾏Y = Y + X后，我们会发现id(Y)指向另⼀个位置。这是因为Python⾸先计算Y + X，为结果分配新的内存，然后使Y指向内存中的这个新位置。

In [59]:
print(y)
before = id(y)
print(before)
print(x)
y = x +y
print(y)
print(id(y))
id(y) == before

tensor([[60, 60, 60, 60],
        [61, 61, 61, 61],
        [42, 47, 52, 57]])
1851830340800
tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])
tensor([[72, 72, 72, 72],
        [73, 73, 73, 73],
        [50, 56, 62, 68]])
1851830291568


False

这可能是不可取的，原因有两个：
1. ⾸先，我们不想总是不必要地分配内存。在机器学习中，我们可能有数百兆的参数，并且在⼀秒内多次更新所有参数。通常情况下，我们希望原地执⾏这些更新；
2. 如果我们不原地更新，其他引⽤仍然会指向旧的内存位置，这样我们的某些代码可能会⽆意中引⽤旧的参数。
幸运的是，执⾏**原地操作**⾮常简单。我们可以使⽤**切⽚表⽰法**将操作的结果分配给先前分配的数组，例如Y[:]= <expression>。为了说明这⼀点，我们⾸先创建⼀个新的矩阵Z，其形状与另⼀个Y相同，使⽤zeros_like来分配⼀个全0的块。

In [65]:
Z = torch.zeros_like(y)
print(Z)
print('id(Z):', id(Z))
Z[:] = x + y
print('id(Z):', id(Z))
Z

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])
id(Z): 1851813239600
id(Z): 1851813239600


tensor([[84, 84, 84, 84],
        [85, 85, 85, 85],
        [58, 65, 72, 79]])

如果在后续计算中没有重复使⽤X，我们也可以使⽤X[:] = X + Y或X += Y来减少操作的内存开销。

In [68]:
print(x)
print(id(x))
print(y)
x[:] = x + y
print(x)
print(id(x))

tensor([[12, 12, 12, 12],
        [12, 12, 12, 12],
        [ 8,  9, 10, 11]])
1851809039600
tensor([[72, 72, 72, 72],
        [73, 73, 73, 73],
        [50, 56, 62, 68]])
tensor([[84, 84, 84, 84],
        [85, 85, 85, 85],
        [58, 65, 72, 79]])
1851809039600


In [69]:
before = id(x)
x[:] = x + y
id(x) == before

True

In [78]:
before = id(x)
x += y
id(x) == before

tensor([[732, 732, 732, 732],
        [742, 742, 742, 742],
        [508, 569, 630, 691]])


### 2.1.6 转换为其他Python对象
将深度学习框架定义的张量转换为NumPy张量（ndarray）很容易，反之也同样容易。 torch张量和numpy数组将共享它们的底层内存，就地操作更改⼀个张量也会同时更改另⼀个张量。

In [81]:
A = x.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

要将⼤⼩为1的张量转换为Python标量，我们可以调⽤item函数或Python的内置函数

In [86]:
a = torch.tensor([3.5])
a, a.item(),float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

**小结**
深度学习存储和操作数据的主要接⼝是张量（n维数组）。它提供了各种功能，包括基本数学运算、⼴播、索引、切⽚、内存节省和转换其他Python对象。

**练习**
1. 运⾏本节中的代码。将本节中的条件语句X == Y更改为X < Y或X > Y，然后看看你可以得到什么样的张量。
2. ⽤其他形状（例如三维张量）替换⼴播机制中按元素操作的两个张量。结果是否与预期相同？

In [91]:
x = torch.arange(12).reshape((3,4))
y = torch.tensor([[1,2,3,4],[4,4,4,4],[7,6,5,4]])
x, y, x < y,x > y

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[1, 2, 3, 4],
         [4, 4, 4, 4],
         [7, 6, 5, 4]]),
 tensor([[ True,  True,  True,  True],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [False,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [95]:
m = torch.randn((3,2,1))
n = torch.randn((1,2,3))
m, n, m + n

(tensor([[[-0.7711],
          [ 0.5219]],
 
         [[-0.1672],
          [ 0.3687]],
 
         [[ 0.6326],
          [ 0.6782]]]),
 tensor([[[-0.8963, -1.8768,  1.0317],
          [ 1.1989,  0.5655, -1.1424]]]),
 tensor([[[-1.6674, -2.6479,  0.2605],
          [ 1.7208,  1.0874, -0.6205]],
 
         [[-1.0634, -2.0440,  0.8645],
          [ 1.5676,  0.9342, -0.7737]],
 
         [[-0.2636, -1.2442,  1.6643],
          [ 1.8771,  1.2437, -0.4642]]]))