### 2.3.1 标量

In [7]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)
x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

### 2.3.2 向量
向量可以被视为标量值组成的列表。\
当向量表⽰数据集中的样本时，它们的值具有⼀定的现实意义。例如，如果我们正在训练⼀个模型来预测贷款违
约⻛险，可能会将每个申请⼈与⼀个向量相关联，其分量与其收⼊、⼯作年限、过往违约次数和其他因素相
对应。如果我们正在研究医院患者可能⾯临的⼼脏病发作⻛险，可能会⽤⼀个向量来表⽰每个患者，其分量
为最近的⽣命体征、胆固醇⽔平、每天运动时间等。\
在数学表⽰法中，向量通常记为**粗体、⼩写**的符号（例如， x、 y和z)）。\
⼈们通过⼀维张量表⽰向量。⼀般来说，张量可以具有任意⻓度，取决于机器的内存限制。

In [16]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

In [17]:
x[3]

tensor(3)

**⻓度、维度和形状**
向量只是⼀个数字数组，就像每个数组都有⼀个⻓度⼀样，每个向量也是如此。\

In [18]:
len(x) # 长度、维度

4

**形状**
当⽤张量表⽰⼀个向量（只有⼀个轴）时，我们也可以通过.shape属性访问向量的⻓度。形状（shape）是⼀
个元素组，列出了张量沿每个轴的⻓度（维数）。对于只有⼀个轴的张量，形状只有⼀个元素。

In [29]:
x.shape

torch.Size([4])

请注意，维度（dimension）这个词在不同上下⽂时往往会有不同的含义，这经常会使⼈感到困惑。为了清楚
起⻅，我们在此明确⼀下：向量或轴的维度被⽤来表⽰向量或轴的⻓度，即向量或轴的元素数量。然⽽，张
量的维度⽤来表⽰张量具有的轴数。在这个意义上，张量的某个轴的维数就是这个轴的⻓度。
### 2.3.3 矩阵
正如向量将标量从零阶推⼴到⼀阶，矩阵将向量从⼀阶推⼴到⼆阶。矩阵，我们通常⽤**粗体、⼤写**字⺟来表
⽰（例如， X、 Y和Z），在代码中表⽰为具有两个轴的张量。\
当调⽤函数来实例化张量时，我们可以通过指定两个分量m和n来创建⼀个形状为m × n的矩阵。

In [50]:
A = torch.arange(20).reshape(5,4)
print(A)
A[3]

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])


tensor([12, 13, 14, 15])

现在在代码中访问矩阵的转置。

In [51]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

作为⽅阵的⼀种特殊类型，对称矩阵（symmetric matrix） A等于其转置：这⾥定义⼀个对称矩阵B：

In [52]:
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B)
print(B.T)
B == B.T # 现在我们将B与它的转置进⾏⽐较。

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

矩阵是有⽤的数据结构：它们允许我们组织具有不同模式的数据。\
例如，我们矩阵中的⾏可能对应于不同的
房屋（数据样本），⽽列可能对应于不同的属性。
### 2.3.4 张量
